set-option -sa terminal-overrides ",xterm*:Tc"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'kiyoon/treemux'

set -g @tmux-gruvbox 'dark256'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

run-shell ~/.config/tmux/plugins/tmux-session-wizard/session-wizard.tmux
run '~/.tmux/plugins/tpm/tpm'
set -g @treemux-tree-nvim-init-file '~/.config/tmux/plugins/treemux/configs/treemux_init.lua'
set -g @treemux-nvim-command 'NVIM_APPNAME=nvim-treemux nvim'
